### ISSUE TITLE
Ajouter les projections légales des collectivités d'outremer

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/project-legal#153]
pour l'intégration des COM ajouter les projections dans le fichier https://github.com/BaseAdresseNationale/project-legal/blob/master/projections.json pour les territoires suivants : 

- Saint Barthélemy 
- Nouvelle Calédonie
- Polynésie française

**Comment by jdesboeufs** [comment]
Saint-Barthélémy et Saint-Martin c'est déjà bon : https://github.com/BaseAdresseNationale/project-legal/blob/master/projections.json#L11

Il manque aussi Wallis-et-Futuna, mais il est possible que ce soit la même que pour la Polynésie.

L'action de retrouver les informations-clés est chez @FrederiqWilliams.

**Comment by mmortier** [comment]
[projectionsIGNF.docx](https://github.com/BaseAdresseNationale/project-legal/files/8714088/projectionsIGNF.docx)

**Comment by vinsag** [comment]
Il faudrait determiner les sources que nous avons utilisé car nous n'avons pas forcément les référentiels identiques.
Pour Polynésie française : utilisons nous les données de data.gouv.fr ? Fréquence de mise à jour ?
Pour Nouvelle Calédonie: Utilisons nous les ressources du site https://georep.nc ?

**Comment by jdesboeufs** [comment]
Ce dépôt n'est là que pour gérer les projections légales de coordonnées géographiques.
Je crois que cela relève exclusivement de la commission Géodésie du CNIG, en lien avec l'IGN.

Pour les contours ils sont déjà pris en charge ici : https://github.com/etalab/contours-administratifs.
